### ISSUE TITLE
Configuration Files

### ISSUE THREAD

**Issue by ericdoerheit** [BoschXDK/Bosch-IoT-Suite#4]
Nice Project! It would be great, if you could provide exemplary configuration files, that must be placed on the SD card. Or are there any configuration examples given in the example projects of the XDK?

Thanks!

**Comment by ChrisRKoch84** [comment]
Eric,
Thank you for your comment.  There is an example network and data configuration file located at the end of the tutorial on our webpage (http://xdk.bosch-connectivity.com/boschiotsuite).  These examples you can simply copy and paste into a text file stored on an SD Card.

**Comment by ChrisRKoch84** [comment]
Eric,
I went ahead and added the example text files you suggested.  We decided this would make life a bit easier for all.  Thank you for that suggestion.  For connection to the Bosch IoT Suite however users will still need to edit the NCONFIG.txt file to include the server address and port information from the tutorial I point to in my previous post.
Thank you,
Christopher Koch
